version: '3.8'

services:
  backendapi:
    image: ${DOCKER_REGISTRY-}backendapi
    build:
      context: .
      dockerfile: BackendApi/Dockerfile

  webappfront:
    image: ${DOCKER_REGISTRY-}webappfront
    build:
      context: .
      dockerfile: WebAppFront/Dockerfile
      # Sqlserver
  # sqlserver:
  #    image: mcr.microsoft.com/mssql/server:2022-latest
  #    environment:
  #       - ACCEPT_EULA=Y
  #       - MSSQL_SA_PASSWORD=nikr54684!
  #    ports:
  #       - "1433:1433"