version: '3.8'

services:
 backendapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080" 
      - "8081:8081" 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

 webappfront:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      -  ConnectionStrings__WebAppUserConnection=Server=host.docker.internal,1433;Database=uniksqlserver;User=sa;Password=nikr54684!;TrustServerCertificate=True; # Sqlserver
    ports:
      - "8082:8080" 
      - "8083:8081" 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - sqlserver # Sqlserver
  
  