version: '3.8'

services:
  backendapi:
    image: ${DOCKER_REGISTRY-}backendapi
    build:
      context: .
      dockerfile: BackedApi/Dockerfile

  webappfront:
    image: ${DOCKER_REGISTRY-}webappfront
    build:
      context: .
      dockerfile: WebAppFront/Dockerfile

